logging:
  level:
    ROOT: INFO
    com.pongift20: DEBUG
    org.apache.ibatis: DEBUG
  file:
    name: /home/user/pongift-marketplace/logs/pongift-marketplace-tb.log
    max-history: 31
    max-size: 500MB
spring:
  datasource:
    url: jdbc:mariadb://tb.pongift.com:8806/marketplace?autoReconnect=true&noAccessToProcedureBodies=true&useSSL=false&allowMultiQueries=true&serverTimezone=UTC&characterEncoding=utf8
    driver-class-name: org.mariadb.jdbc.Driver
    username: market0709
    password: market001
  main:
    allow-bean-definition-overriding: true
server:
  port: '15111'
  servlet:
    context-path: /api
    session:
      cookie:
        name: MARKETPLACE_SESSIONID
        secure: true
        http-only: true
      timeout: 1800
      persistent: false
mybatis:
  type-aliases-package: com.pongift20.marketplace.backend.goods.model.dto,
    com.pongift20.marketplace.backend.user.model.dto,
    com.pongift20.marketplace.backend.order.model.dto,
    com.pongift20.marketplace.backend.category.model.dto,
    com.pongift20.marketplace.backend.giftcard.model.dto,
    com.pongift20.marketplace.backend.store.model.dto,
    com.pongift20.marketplace.backend.security.model.dto,
    com.pongift20.marketplace.backend.partner.kyobo.model.dto
  mapper-locations: classpath:mapper/*.xml
  configuration:
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
    mapUnderscoreToCamelCase: true
pongift:
  api-host: http://tb.pongift.com:914/
  barcode-host: //dev-giftcard.pongift.com/view/
  pay-host: http://dev-pay2.pongift.com/
  main-page: //dev-marketplace.pongift.com/
  error-page: //dev-marketplace.pongift.com/error
  terms-page: //dev-marketplace.pongift.com/join/terms?partner=kyobo
kyobo:
  url: www.kyobo.com
  api-host: https://dapi.ext-open-service.com
  iv: 20230831192212